<?php
var_dump($_GET, $_POST);


echo var_dump();

?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap 101 Template</title>

 
    <link href="css/bootstrap.min.css" rel="stylesheet">


  </head>
  <body>
    

<form method="post" action "board.phtml">
  <div class="form-group">


    <label name="email" for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>

<div class="form-group">
    <label for="exampleInputEmail1">Name</label>
    <input name="name" type="text" class="form-control" id="exampleInputEmail1" placeholder="name">
  </div>

<div class="form-group">
    <label for="exampleInputEmail1">Comment</label>
    <input name="comment" type="text" class="form-control" placeholder="comment">
  </div>
  
  
  <button type="submit" class="btn btn-default">Submit</button>

</form>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>